apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: guestbook
        tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: venky01/frontendphp:v12
        env:
        - name: GET_HOSTS_FROM
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80