apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  namespace: backend
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30125
  selector:
    app: redis
    role: leader
    tier: backend